Repository CS2103JAN2018-W10-B4/main, pull requests merged in 2018-04, with the labels that each got.

#103 Link Delete Appointment to Calendar
  src/main/java/seedu/address/commons/events/model/AppointmentDeletedEvent.java
  src/main/java/seedu/address/commons/events/model/NewAppointmentAddedEvent.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/seedu/address/commons/event/AppointmentDeletedEventTest.java
  src/test/java/seedu/address/commons/event/NewAppointmentAddedEventTest.java
Labels: milestone1.4, owner.Josh, type.enhancement, type.tests

#95 PR for import and export contacts commands closes #29, closes #105, closes #106
  build.gradle
  data/Test_contacts.csv
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportContactDiagram.png
  docs/images/ImportContactDiagram.png
  docs/images/notification_flag.png
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/seedu/address/logic/commands/ExportContactsCommand.java
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportContactsCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportContactsCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
Labels: milestone1.4, owner.Lucas

#109 Added @@author and added *.bat to .gitignore closes #107, closes #108
  .gitignore
  src/main/java/seedu/address/logic/commands/ExportContactsCommand.java
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/main/java/seedu/address/logic/parser/ExportContactsCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportContactsCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
Labels: type.documentation, type.fixed

#120 Updated User Guide
  docs/UserGuide.adoc
Labels: milestone1.4, owner.Josh, type.documentation

#119 Created Implementation segment for Scheduling module
  docs/DeveloperGuide.adoc
  docs/diagrams/AddAppointmentSequenceDiagram.pptx
  docs/diagrams/DeleteAppointmentSequenceDiagram.pptx
  docs/diagrams/DeleteBeforeSequenceDiagram.pptx
  docs/images/AddAppointmentSequenceDiagram.png
  docs/images/CalendarView.PNG
  docs/images/DeleteAppointmentSequenceDiagram.png
  docs/images/DeleteBeforeSequenceDiagram.png
Labels: milestone1.4, owner.Josh, type.documentation

#123 Update About Us & App Icon & App Name
  docs/AboutUs.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/addsurance_logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: milestone1.4, owner.Josh, type.documentation, type.enhancement

#124 Collated code v1.4
  Collate-TUI.jar
  collated/functional/jlks96.md
  collated/functional/luca590.md
  collated/functional/ng95junwei.md
  collated/test/jlks96.md
  collated/test/luca590.md
  collated/test/ng95junwei.md
Labels: milestone1.4, owner.Josh, type.documentation

#125 Updated UI image
  docs/images/CalendarView.png
  docs/images/Ui.png
Labels: milestone1.4, owner.Josh, type.documentation

#150 Added more logic and fixed bug for scheduling
  src/main/java/seedu/address/commons/events/ui/MaxZoomInEvent.java
  src/main/java/seedu/address/commons/events/ui/MaxZoomOutEvent.java
  src/main/java/seedu/address/commons/events/ui/ZoomSuccessEvent.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ZoomInCommand.java
  src/main/java/seedu/address/logic/commands/ZoomOutCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/ClashingAppointmentException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/seedu/address/commons/event/MaxZoomInEventTest.java
  src/test/java/seedu/address/commons/event/MaxZoomOutEventTest.java
  src/test/java/seedu/address/commons/event/ZoomSuccessEventTest.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ZoomInCommandTest.java
  src/test/java/seedu/address/logic/commands/ZoomOutCommandTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
Labels: milestone1.5rc, owner.Josh, type.enhancement, type.tests

#151 Created Calendar Go Forward Backward Commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/logic/CalendarGoBackwardEvent.java
  src/main/java/seedu/address/commons/events/logic/CalendarGoForwardEvent.java
  src/main/java/seedu/address/logic/commands/GoBackwardCommand.java
  src/main/java/seedu/address/logic/commands/GoForwardCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/seedu/address/commons/event/CalendarGoBackwardEventTest.java
  src/test/java/seedu/address/commons/event/CalendarGoForwardEventTest.java
  src/test/java/seedu/address/logic/commands/GoBackwardCommandTest.java
  src/test/java/seedu/address/logic/commands/GoForwardCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
Labels: milestone1.5rc, owner.Josh, type.documentation, type.enhancement, type.tests

#152 claim author for code
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/model/UniqueTemplateListTest.java
  src/test/java/seedu/address/model/email/TemplateTest.java
Labels: milestone1.4, owner.Jun Wei, type.documentation

#154 Updated DG
  docs/DeveloperGuide.adoc
  docs/diagrams/AppointmentClassDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/AppointmentClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: milestone1.5rc, owner.Josh, type.documentation

#155 Implement add template
  src/main/java/seedu/address/logic/commands/AddTemplateCommand.java
  src/main/java/seedu/address/logic/parser/AddTemplateCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/email/Template.java
  src/main/java/seedu/address/model/email/UniqueTemplateList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTemplateCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTemplateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/email/TemplateTest.java
  src/test/java/seedu/address/testutil/TemplateBuilder.java
Labels: milestone1.5rc, owner.Jun Wei, type.enhancement, type.task, type.tests

#161 Edit UI
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BlueGreyTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
Labels: milestone1.5rc, owner.Josh, type.enhancement

#162 Update UG DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UIExplanations.pptx
  docs/diagrams/commandScreenShot.pptx
  docs/images/CalendarView.png
  docs/images/UIExplanations.png
  docs/images/Ui.png
  docs/images/aaScreenshot.png
  docs/images/daScreenshot.png
  docs/images/gbScreenshot.png
  docs/images/gfScreenshot.png
  docs/images/ziScreenshot.png
  docs/images/zoScreenshot.png
Labels: milestone1.5rc, owner.Josh, type.documentation

#163 Delete template command
  src/main/java/seedu/address/logic/commands/AddTemplateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTemplateCommand.java
  src/main/java/seedu/address/logic/parser/AddTemplateCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTemplateCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/email/UniqueTemplateList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTemplateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTemplateCommandParserTest.java
  src/test/java/seedu/address/model/UniqueTemplateListTest.java
  src/test/java/seedu/address/testutil/TemplateBuilder.java
Labels: milestone1.5rc, owner.Jun Wei, type.story, type.tests

#160 Updated docs & added PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddTemplateSequenceDiagram.png
  docs/images/DeleteTemplateSequenceDiagram.png
  docs/images/TemplateClassDiagram.png
  docs/team/junwei.adoc
Labels: milestone1.5rc, type.documentation, type.task

#164 Added PPP jlks96
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jlks96.adoc
Labels: milestone1.5rc, owner.Josh, type.documentation

#165 Cleaning up commented out code in SortCommandTest
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: milestone1.5rc, owner.Lucas

#171 Collate code & Add Sample Data
  collated/functional/jlks96-reused.md
  collated/functional/jlks96.md
  collated/functional/luca590.md
  collated/functional/ng95junwei.md
  collated/test/jlks96-reused.md
  collated/test/jlks96.md
  collated/test/luca590.md
  collated/test/ng95junwei.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/systemtests/AddAliasSystemTest.java
  src/test/java/systemtests/ClearAliasSystemTest.java
  src/test/java/systemtests/DeleteAliasSystemTest.java
  src/test/java/systemtests/EditAliasSystemTest.java
  src/test/java/systemtests/FindAliasSystemTest.java
  src/test/java/systemtests/HelpAliasSystemTest.java
  src/test/java/systemtests/SelectAliasSystemTest.java
Labels: milestone1.5rc, owner.Josh, type.documentation, type.enhancement

#172 Link from AboutUs to ppp
  docs/AboutUs.adoc
Labels: milestone1.5rc, owner.Josh, type.documentation

#176 Restore gradlew.bat
  .gitignore
  gradlew.bat
Labels: milestone1.5, owner.Josh

#178 Update documents
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AppointmentClassDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UIExplanations.pptx
  docs/images/AppointmentClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UIExplanations.png
  docs/images/aaActivityDiagram.png
  docs/images/luca590.jpg
  docs/team/jlks96.adoc
Labels: milestone1.5, owner.Josh, type.documentation

#179 Fixed coding style, formatting and comments
  src/main/java/seedu/address/commons/events/logic/CalendarGoBackwardEvent.java
  src/main/java/seedu/address/commons/events/logic/CalendarGoForwardEvent.java
  src/main/java/seedu/address/commons/events/logic/ZoomInEvent.java
  src/main/java/seedu/address/commons/events/logic/ZoomOutEvent.java
  src/main/java/seedu/address/commons/events/model/AppointmentDeletedEvent.java
  src/main/java/seedu/address/commons/events/model/NewAppointmentAddedEvent.java
  src/main/java/seedu/address/commons/events/ui/MaxZoomInEvent.java
  src/main/java/seedu/address/commons/events/ui/MaxZoomOutEvent.java
  src/main/java/seedu/address/commons/events/ui/ZoomSuccessEvent.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBeforeCommand.java
  src/main/java/seedu/address/logic/commands/ZoomInCommand.java
  src/main/java/seedu/address/logic/commands/ZoomOutCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PersonIsAddedBeforeDateInputAndContainsTagsPredicate.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/EndTime.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/ClashingAppointmentException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/person/DateAddedIsBeforeDateInputPredicate.java
  src/main/java/seedu/address/model/tag/UniqueTagListContainsTagsPredicate.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: milestone1.5, owner.Josh, type.fixed

#183 PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AppointmentClassDiagram.png
  docs/images/DeleteAppointmentSequenceDiagram.png
  docs/images/DeleteBeforeSequenceDiagram.png
  docs/images/UIExplanations.png
  docs/images/aaActivityDiagram.jpg
  docs/images/aaActivityDiagram.png
  docs/images/aaScreenshot.png
  docs/images/daScreenshot.png
  docs/images/gbScreenshot.png
  docs/images/gfScreenshot.png
  docs/images/ziScreenshot.png
  docs/images/zoScreenshot.png
  docs/team/jlks96.adoc
  docs/team/johndoe.adoc
Labels: milestone1.5, owner.Josh, type.documentation

#182 Update DG (add manual testing instructions) & fix stuff
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/logic/UpdateAppointmentsEvent.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/seedu/address/commons/event/UpdateAppointmentsEventTest.java
Labels: milestone1.5, owner.Josh, type.documentation, type.fixed

#185 sort alias is now 'so' closes #177
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: milestone1.5, owner.Lucas

#186 Edit tests
  collated/functional/jlks96-reused.md
  collated/functional/jlks96.md
  collated/functional/luca590.md
  collated/functional/ng95junwei.md
  collated/test/jlks96.md
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/appointment/TimeTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsAndAppointments.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/systemtests/DeleteBeforeAliasSystemTest.java
  src/test/java/systemtests/DeleteBeforeCommandSystemTest.java
Labels: milestone1.5, owner.Josh, type.tests

#187 Update UG
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportContactsCommand.java
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/main/java/seedu/address/logic/parser/ExportContactsCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportContactsCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
Labels: milestone1.5, owner.Josh, type.documentation

#188 Update ppp
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
  docs/team/jlks96.adoc
Labels: milestone1.5, owner.Josh, type.documentation

#181 Final demo fixes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/GmailUtil.java
  src/main/java/seedu/address/logic/commands/DeleteTemplateCommand.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTemplateCommandParser.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
  src/main/java/seedu/address/model/email/UniqueTemplateList.java
  src/main/java/seedu/address/model/email/exceptions/DuplicateTemplateException.java
  src/main/java/seedu/address/model/email/exceptions/TemplateNotFoundException.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTemplateCommandParserTest.java
Labels: milestone1.5, owner.Jun Wei, type.bug, type.documentation, type.fixed

#194 Final touchup
  docs/images/ExportContactDiagram.png
  docs/images/ImportContactDiagram.png
Labels: milestone1.5, owner.Josh

#195 Collated code
  collated/functional/luca590.md
  collated/functional/ng95junwei.md
  collated/test/luca590.md
  collated/test/ng95junwei.md
Labels: milestone1.5, owner.Josh

#196 Final Final touch up
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: milestone1.5, owner.Josh, type.documentation
