Repository CS2103JAN2018-W10-B4/main, pull requests merged in 2018-03, with the labels that each got.

#36 Improve find command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/NameContainsFullKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsFullKeywordsPredicateTest.java
  src/test/java/systemtests/FindAliasSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: documentation, enhancement, milestone1.1, owner: Jun Wei

#37 Add NFR and Use case
  docs/DeveloperGuide.adoc
Labels: documentation, owner: Jun Wei

#38 Update Doc for v1.1
  README.adoc
  docs/AboutUs.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/jlks96.jpg
  docs/images/luca590.jpg
  docs/images/ng95junwei.jpg
Labels: documentation, milestone1.1, owner: Josh

#43 Update docs for email
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation, enhancement, milestone1.2, owner: Jun Wei

#48 Added Calendar UI
  build.gradle
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/exceptions/CalendarPanelHandle.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpAliasSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: enhancement, milestone1.2, owner: Josh

#52 Update user & developer guide (milestone 1.2)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DeleteBeforeSequenceDiagram.pptx
  docs/images/DeleteBeforeSequenceDiagram.png
  docs/images/Ui.png
Labels: documentation, milestone1.2, owner: Josh

#44 Import csv class
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ImportContactsCommandParser.java
  src/test/java/seedu/address/logic/parser/ImportContactsCommandTest.java
Labels: documentation, enhancement, owner: Lucas, to update tests

#46 Add email command
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/seedu/address/commons/util/GmailUtil.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EmailCommandParser.java
  src/main/resources/client_secret.json
Labels: enhancement, owner: Jun Wei, task, to update tests

#69 Added author tag (jlks96)
  src/main/java/seedu/address/logic/commands/DeleteBeforeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteBeforeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PersonIsAddedBeforeDateInputAndContainsTagsPredicate.java
  src/main/java/seedu/address/model/person/DateAdded.java
  src/main/java/seedu/address/model/person/DateAddedIsBeforeDateInputPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/UniqueTagListContainsTagsPredicate.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/resources/view/CalendarPanel.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteBeforeCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteBeforeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/PersonIsAddedBeforeDateInputAndContainsTagsPredicateTest.java
  src/test/java/seedu/address/model/person/DateAddedIsBeforeDateInputPredicateTest.java
  src/test/java/seedu/address/model/person/DateAddedTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListContainsTagsPredicateTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalDates.java
  src/test/java/seedu/address/testutil/TypicalPersonsWithAutoDateGeneration.java
  src/test/java/seedu/address/testutil/TypicalTags.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteBeforeAliasSystemTest.java
  src/test/java/systemtests/DeleteBeforeCommandSystemTest.java
  src/test/java/systemtests/EditAliasSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: milestone1.3, owner.Josh

#58 Update email tests
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: milestone1.3, owner.Jun Wei, type.tests

#75 -updated UG
  docs/UserGuide.adoc
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
Labels: milestone1.3, owner.Josh, type.documentation

#79 Create Add Appointment Function
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteBeforeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
Labels: milestone1.3, owner.Josh, type.enhancement, type.tests

#83 Link to calendar
  src/main/java/seedu/address/commons/events/ui/NewAppointmentAddedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/event/NewAppointmentAddedEventTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: milestone1.3, owner.Josh, type.enhancement

#82 Update template tests
  src/main/java/seedu/address/model/email/Template.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UniqueTemplateListTest.java
  src/test/java/seedu/address/model/email/TemplateTest.java
Labels: milestone1.3, owner.Jun Wei, type.task, type.tests

#90 Updated DG v1.3
  docs/DeveloperGuide.adoc
Labels: milestone1.3, owner.Josh, type.documentation

#102 Add DeleteAppointment command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: milestone1.4, owner.Josh, type.documentation, type.enhancement, type.tests
